version: 2
jobs:
  build:
    working_directory: ~/roesc
    docker:
      - image: circleci/clojure:lein-2.8.3
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx1024m
    steps:
      - checkout
      - restore_cache:
          key: roesc-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: roesc-{{ checksum "project.clj" }}
      - run: lein test
      - run: lein uberjar
      - run: mkdir -p artifacts && mv target/uberjar/roesc-*-standalone.jar artifacts/roesc-b${CIRCLE_BUILD_NUM}-${CIRCLE_TAG}.jar
      - store_artifacts:
          path: artifacts
